name: hpsc
description: A cli for making an html project
version: 1.0.0 # This will never change. Pubspec is just so I can add dependencies

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_console: ^1.0.2

executables:
  hpsc: main.dart